from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time

s=Service('C:\webdriver\chromedrib=ver.exe')
driver = webdriver.ChromiumEdge(service=s)
driver.get("https://idemo.bspb.ru/auth?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fidemo.bspb.ru%2"
           "Flogin%2Fsuccess&prefetch_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fprefetch&force_new_session=true")
time.sleep(2)

driver.set_window_size(1920, 1080)
time.sleep(2)
driver.find_element(By.ID, "login-button").click()
driver.find_element(By.ID, "login-otp-button").click()
time.sleep(2)
driver.find_element(By.ID, "insurance").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='contentbar']/div[3]/a").click()
driver.find_element(By.XPATH, "/html/body/div[8]/div/div/div[3]/button[2]").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='faq-link']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='body']/div[1]/div/ul[2]/li/ul/li[1]/a").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, ".icon-email").click()
driver.find_element(By.ID, "new-message-btn").click()
driver.find_element(By.NAME, "message.topicName").click()
dropdown = driver.find_element(By.NAME, "message.topicName")
time.sleep(2)
driver.find_element(By.XPATH, "//option[. = 'Вопрос по вкладу']").click()
time.sleep(2)
driver.find_element(By.NAME, "message.text").click()
time.sleep(2)
driver.find_element(By.NAME, "message.text").send_keys("11111")
time.sleep(2)
driver.find_element(By.ID, "send-button").click()
time.sleep(3)
driver.switch_to.frame(0)
driver.find_element(By.CSS_SELECTOR, ".uneditable-input").click()
driver.find_element(By.ID, "otp-input").click()
driver.find_element(By.ID, "confirm").click()
time.sleep(3)
driver.find_element(By.ID, "insurance").click()
driver.find_element(By.XPATH, "//*[@id='contentbar']/div[3]/a").click()
driver.find_element(By.XPATH, "/html/body/div[8]/div/div/div[3]/button[1]").click()
time.sleep(3)